### ISSUE TITLE
1 sec delay in rtsp streaming

### ISSUE THREAD

**Issue by Hassan66169** [mzahana/siyi_sdk#10]
Hello,
First of all, Thank you for providing such a helpful API for SIYI Camera.
I am using the SIYI ZR10 camera and connected it to my PC using an Ethernet Cable. I need RTSP streaming so whenever I run test_rtsp.py there is a 1 second delay which is a trouble for me since I need real-time video streaming.

Also when I read the RTSP data using OpenCV I am having the same issue. However, when I connected my system with Skydroid H16 Radio there was only negligible delay in video streaming.

Kindly suggest some improvements.
Regards

**Comment by Hassan66169** [comment]
I think the issue is with the wire. I am getting RTSP with VLC and it has the same 1 second delay.

Thank you

**Comment by mzahana** [comment]
The standard VLC configuration will show delays (mentioned in the README). The package is updated 

Have you tried the test script included in the package?
https://github.com/mzahana/siyi_sdk/blob/main/tests/test_rtsp.py
