### ISSUE TITLE
Unable to connect to camera with IP and UDP working properly

### ISSUE THREAD

**Issue by NickNickering** [mzahana/siyi_sdk#12]
Hello! I'm trying to implement the SDK with ZR10 and Jetson Nano. But I'm facing an issue while running siyi_sdk.py:

`"/home/mikeainsel/Desktop/Camera control/.venv/bin/python" "/home/mikeainsel/Desktop/Camera control/siyi_sdk/siyi_sdk.py"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikeainsel/Desktop/Camera control/siyi_sdk/siyi_sdk.py", line 224, in recvLoop
    self.bufferCallback()
  File "/home/mikeainsel/Desktop/Camera control/siyi_sdk/siyi_sdk.py", line 232, in bufferCallback
    buff,addr = self._socket.recvfrom(self._BUFF_SIZE)
socket.timeout: timed out
 [INFO] 2024-04-14 08:29:23,221 [SIYISDK::disconnect] : Stopping all threads
 [ERROR] 2024-04-14 08:29:23,221 [SIYISDK::connect] :   Failed to connect to camera
 [WARNING] 2024-04-14 08:29:23,589 [SIYISDK::connectionLoop] :  Connection checking loop is stopped. Check your connection!'

 The camera is connected via Ethernet and I already checked the IP connection with 'ping' 
'PING 192.168.144.25 (192.168.144.25) 56(84) bytes of data.
64 bytes from 192.168.144.25: icmp_seq=1 ttl=64 time=0.150 ms
64 bytes from 192.168.144.25: icmp_seq=2 ttl=64 time=0.131 ms
64 bytes from 192.168.144.25: icmp_seq=3 ttl=64 time=0.124 ms'

and 'sudo tcpdump -i any udp port 37260 -vv' (to check UDP connection)
'tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
08:22:01.854222 IP (tos 0x0, ttl 64, id 56187, offset 0, flags [DF], proto UDP (17), length 38)
    mikeainsel-desktop.58087 > mikeainsel-desktop.37260: [bad udp cksum 0xa1a7 -> 0x2ea6!] UDP, length 10
08:22:02.976377 IP (tos 0x0, ttl 64, id 56345, offset 0, flags [DF], proto UDP (17), length 38)
    mikeainsel-desktop.58087 > mikeainsel-desktop.37260: [bad udp cksum 0xa1a7 -> 0x2ea6!] UDP, length 10
08:22:04.098226 IP (tos 0x0, ttl 64, id 56588, offset 0, flags [DF], proto UDP (17), length 38)
    mikeainsel-desktop.58087 > mikeainsel-desktop.37260: [bad udp cksum 0xa1a7 -> 0x2ea6!] UDP, length 10
08:25:59.722293 IP (tos 0x0, ttl 64, id 58143, offset 0, flags [DF], proto UDP (17), length 38)
    mikeainsel-desktop.56627 > mikeainsel-desktop.37260: [bad udp cksum 0xa1a7 -> 0x345a!] UDP, length 10
08:26:00.844058 IP (tos 0x0, ttl 64, id 58306, offset 0, flags [DF], proto UDP (17), length 38)
    mikeainsel-desktop.56627 > mikeainsel-desktop.37260: [bad udp cksum 0xa1a7 -> 0x345a!] UDP, length 10
'
 How can I address this issue?
 I'm new to programming, so I'm sorry if this sort of error I'm facing is stupid :)

**Comment by tirpudevk111** [comment]
Did you get the solution to this issue? I am also facing the same with ZR30.
