### ISSUE TITLE
Accessing the siyi a8 mini video stream 

### ISSUE THREAD

**Issue by snowIsNotAvaiable** [mzahana/siyi_sdk#13]
Hello !

So, my siyi camera is currently connected to a raspberry pi via ethernet on the eth0 interface with a static ip of 192.168.1.143.. The Raspberry is on the same wifi network as my macbook which i want to use as a sort of ground station.. I Have the code in PyCharm on my macbook and should have all the neccessary dependencies on both my mac and the pi. How exactly do i setup a realtime stream of the siyi cam and access it through the code on my mac ?

Any help would be much appreciated !

**Comment by mzahana** [comment]
I think you need to setup your network correctly.
The example provided in this package assumes that you connect the camera to tour PC (or RPi/Jetson) directly. The camera creates its own network interface. If the camera is not directly connected to your "Ground station", then you may need to do some re-routing (please Google it).
