### ISSUE TITLE
SIYI message self._seq variable does not reset to 0.

### ISSUE THREAD

**Issue by SmolBoi96** [mzahana/siyi_sdk#5]
SIYI message self._seq variable starts at 0 and increments everytime a request function is used in the SDK. When it hits 65536 it gives this warning:

[SIYISDK::incrementSEQ] :   Sequence value is greater than 65535. Resetting to zero

But the variable does not reset to 0 and this warning keeps showing and the request does not complete.

I propose to add this line after line 147 in siyi-message.py: self._seq = 0

**Comment by mzahana** [comment]
Done. Thanks @SmolBoi96
