### ISSUE TITLE
Node Js Implementation of SiYi Camera SDK

### ISSUE THREAD

**Issue by AhlawatAnup** [mzahana/siyi_sdk#7]
Hi , 
https://github.com/AhlawatAnup/SiyiA8MiniSDK
This is the Node Js Implementation of Siyi Camera SDK. Which Enables you to control the camera directly from web browser.

@mzahana Thanks for python SDK. Won't be possible without it.

looking fwd to expand it with more supports.

Currently It supports Zoom-In, Zoom-out, and gimbal rotations.

**Comment by mzahana** [comment]
Thanks @AhlawatAnup for your contribution
